apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: dev
  name: create-react-app-template
  title: Create React App Template
  description: |
    Create new React app
  labels:
    version: 0.0.1
    visibility: private
  tags:
    - custom
spec:
  owner: group:default/devhub
  type: service

  parameters:
    - title: Component Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          pattern: '^[a-z0-9-]+$'
        description:
          title: Description
          type: string
          description: A brief description of the component
    - title: Ownership
      required:
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: The team that owns this component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
    - title: Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetchBase
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
