apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: dev
  name: nodejs-template
  title: Node.js Template
  description: |
    An example template for the scaffolder that creates a simple Node.js service.
    \
    THIS IS THE INT VERSION. TEST IT INSIDE AND OUT.
    \
    Further customize this template to fit your project's requirements.
  labels:
    version: 1.0.0
    visibility: restricted
  tags:
    - experimental
spec:
  owner: group:default/platform-team
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          owner: ${{ user.entityRef }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: notify
      name: Notify
      action: notification:send
      input:
        recipients: entity
        entityRefs:
          - ${{ user.entityRef }}
        title: 'Template executed'
        info: 'Your template has been executed'
        severity: 'normal'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
